#docker-compose up -d
# docker run -it ghcr.io/openuc2/imswitch-aiortc-react:latest
# docker run -it ghcr.io/openuc2/imswitch-docker-arm64-noqt:latest 
version: '3.8'


services:
  imswitch-aiortc-react:
    image: ghcr.io/openuc2/imswitch-aiortc-react:latest
    ports:
      - "5000:5000"
      - "8001:8001"
    platform: linux/arm64/v8
    environment:
      - NODE_ENV=production

  imswitch-docker-amd64-noqt:
    image: ghcr.io/openuc2/imswitch-docker-arm64-noqt:latest 
    privileged: true
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production

networks:
  default:
    external:
      name: my-network
