name: imswitch-docker-arm64-noqt
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openuc2-imswitch-arm64-noqt

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/HIK/dockerfile
          push: true
          platforms: linux/arm64
          tags: ghcr.io/openuc2/imswitch-docker-arm64-noqt:latest
          labels: ${{ steps.meta.outputs.labels }}
