name: imswitch-bundle

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:



  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .
        python3 -m pip install pyinstaller==5.4.1
      shell: bash
    - name: Build bundle
      run: |
        pyinstaller imswitch.spec
        cd dist
        cd ImSwitch
        dir 
    - name: Upload updated .exe
      uses: actions/upload-artifact@v2
      with:
        name: imswitch-updated-exeonly
        path: dist/ImSwitch/ImSwitch.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: imswitch-${{ matrix.os }}
        path: dist
        
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{steps.version.outputs.version}}
        tag_name: ${{github.ref}}
        body_path: CHANGELOG.md
      env:
          GITHUB_TOKEN: ${{github.token}}
    
    - name: upload windows-exe-update artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .dist/ImSwitch/ImSwitch.exe
        asset_name: ImSwitch.exe
        asset_content_type: application/exe
 

